spring:
  profiles:
    active: dev
server:
  servlet:
   context-path: /backend
cloud:
  aws:
    stack:
      auto: false
rds:
  identifier:  ${RDS_IDENTIFIER:ma-oketanisu-rds}
  password: ${RDS_PASSWORD:postgres}